spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/analyticsdb
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: analytics-service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer