server:
  port: 8084

spring:
  application:
    name: alert-service
#  kafka:
#    bootstrap-servers: kafka:9092
#    consumer:
#      group-id: alert-service-group
#      auto-offset-reset: earliest
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring.cloud.config:
  uri: http://config-server:8888
  name: alert-service
  enabled: false

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics,prometheus
#  metrics:
#    export:
#      prometheus:
#        enabled: true