server:
  port: 8086

spring:
  application:
    name: analytics-service
  data:
    mongodb:
      uri: mongodb+srv://niteshsingh6206:IzEoACREJVGhWwD9@cluster0.0vtamtx.mongodb.net/analyticsdb?retryWrites=true&w=majority&appName=Cluster0
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: analytics-service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#spring.cloud.config:
#  uri: http://config-server:8888
#  name: analytics-service


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true