server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      enabled: false

  application:
    name: task-service
#  kafka:
#    bootstrap-servers: kafka:9092
#    consumer:
#      group-id: task-service-group
#      auto-offset-reset: earliest
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#  config:
#    import: configserver:http://localhost:8751


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#spring.cloud.config:
#  uri: http://config-server:8888
#  name: task-service
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics,prometheus
#  metrics:
#    export:
#      prometheus:
#        enabled: true