spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/api/resources/**
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**
        - id: incident-service
          uri: lb://incident-service
          predicates:
            - Path=/api/incidents/**
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**